### ISSUE TITLE
Screen Flashes When Actuating Hinged/Animated Door

### ISSUE THREAD

**Issue by gammaleak** [Jmr3366/Lib_ActionPads#30]
Description: Intermittently (about 40% - 60% of the time), the screen flashes (looks like solid blue, but it goes by fast) when actuating a hinged/animated door. This is not a huge deal but it would be nice if it didn't happen.

Steps to Repeat:
1. Set up a fully working hinged/animated door.
2. Click on the actuator token to open/close it.

Observed Behavior:
Much of the time, the screen flashes before the animation takes place.

Expected Behavior:
The animation occurs without any other graphical anomalies.

**Comment by gammaleak** [comment]
After closing and re-opening MapTool, this issue appears to have gone away. Possibly it was a high memory usage issue unrelated to LibActionPads.

**Comment by Jmr3366** [comment]
I also wanted to share since this "flash" takes place when overlays are drawn, if you have the Designer open, it will help to minimize it as it "redraws" when open and selecting any ActionPad.

**Comment by Jmr3366** [comment]
In v2.22 I have made some changes to reduce this.
As I can find improvements I'll append them here
